apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dl380x4236-infrastructure
  namespace: flux-system
spec:
  serviceAccountName: kustomize-controller
  interval: 1m0s
  path: ../infrastructure/dl380x4236
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
