apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: eric-tm-ingress-controller-cr-crd
  namespace: flux-system
spec:
  serviceAccountName: kustomize-controller
  interval: 1m0s
  path: infrastructure/base/eric-crds/deployment/eric-tm-ingress-controller-cr-crd
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
