apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/eric-eea-poc
namespace: eric-eea-ns
patches:
  - patch: |
      apiVersion: kustomize.toolkit.fluxcd.io/v1
      kind: Kustomization
      metadata:
        name: eric-eea-poc-repo
      spec:
        path: /apps/dl380x4236/eric-eea-ns
    target:
      kind: Kustomization
      name: eric-eea-poc
