apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: eric-tm-ingress-controller-cr-crd
  namespace: flux-system
spec:
  chart:
    spec:
      chart: eric-tm-ingress-controller-cr-crd
      sourceRef:
        kind: HelmRepository
        name: proj-adp-gs-all-helm
        namespace: flux-system
      version: 11.3.0+59
  interval: 1m0s
  serviceAccountName: helm-controller
  targetNamespace: eric-crd-ns
