apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: eric-sec-certm-crd
  namespace: flux-system
spec:
  chart:
    spec:
      chart: eric-sec-certm-crd
      sourceRef:
        kind: HelmRepository
        name: proj-adp-gs-all-helm
        namespace: flux-system
      version: 4.1.0+21
  interval: 1m0s
  serviceAccountName: helm-controller
  targetNamespace: eric-crd-ns
  valuesFrom:
    - kind: ConfigMap
      name: shared-values
      valuesKey: values.yaml