apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: eric-data-document-database-pg-crd
  namespace: flux-system
spec:
  chart:
    spec:
      chart: eric-data-document-database-pg-crd
      sourceRef:
        kind: HelmRepository
        name: proj-adp-gs-all-helm
        namespace: flux-system
      version: 1.4.0
  interval: 1m0s
  serviceAccountName: helm-controller
  targetNamespace: eric-crd-ns
  valuesFrom:
    - kind: ConfigMap
      name: shared-values
      valuesKey: values.yaml

