apiVersion: v1
kind: Secret
metadata:
  name: eric-eea-snmp-alarm-provider-config
  namespace: eric-eea-ns
type: Opaque
stringData:
  config.json: |-
    {
      "agentEngineId": "8000000001020304",
      "kafkaAddress": "eric-eea-fm-eric-data-message-bus-kf",
      "heartbeatInterval": 30,
      "trapTargets": [
        {
           "address":eric-eea-snmp-server.utf-service.svc.cluster.local,
           "port":"162",
           "user":"traptest",
           "securityLevel":"authPriv",
           "authPassphrase":"mypassword",
           "authProtocol":"SHA1",
           "privPassphrase":"mypassword",
           "privProtocol":"AES128"
        }
      ]
    }
